Label: "Test"
Characters:
  - Base:
      Name: bennett
      Level: 70
      Element: "pyro"
      BaseHP: 10129
      BaseAtk: 156
      BaseDef: 630
      BaseCR: 0.05
      BaseCD: 0.50
      Constellation: 2
    AscensionBonus:
      ER: 0.2
    TalentLevel:
      attack: 2
      skill: 3
      burst: 6
    Weapon:
      WeaponName: "Festering Desire"
      WeaponRefinement: 5
      WeaponBaseAtk: 510
    WeaponSecondaryStat:
      ER: 0.459
    Artifacts:
      Flower:
        Level: 16
        Set: "Noblesse Oblige"
        Main:
          HP: 3967
        Sub:
          DEF: 44
          ER: 0.065
          CR: 0.097
          CD: 0.07
      Feather:
        Level: 16
        Set: "Noblesse Oblige"
        Main:
          ATK: 258
        Sub:
          ATK%: .117
          DEF: 16
          ER: 0.104
          EM: 42
      Sands:
        Level: 16
        Set: "Noblesse Oblige"
        Main:
          ER: 0.43
        Sub:
          ATK%: 0.163
          HP%: 0.058
          CD: 0.117
          HP: 209
      Goblet:
        Level: 16
        Set: "Noblesse Oblige"
        Main:
          ATK%: 0.387
        Sub:
          ER: 0.097
          HP: 538
          CR: 0.031
          EM: 35
      Circlet:
        Level: 20
        Set: "Thundering Fury"
        Main:
          ATK%: 0.387
        Sub:
          EM: 63
          HP: 209
          CR: 0.031
          ATK: 35
  - Base:
      Name: xiangling
      Level: 80
      Element: "pyro"
      BaseHP: 9638
      BaseAtk: 200
      BaseDef: 593
      BaseCR: 0.05
      BaseCD: 0.50
      Constellation: 6
    AscensionBonus:
      EM: 72
    TalentLevel:
      attack: 6
      skill: 6
      burst: 8
    Weapon:
      WeaponName: "Skyward Spine"
      WeaponRefinement: 1
      WeaponBaseAtk: 674
    WeaponSecondaryStat:
      ER: 0.368
    Artifacts:
      Flower:
        Level: 20
        Set: "Crimson Witch of Flames"
        Main:
          HP: 4780
        Sub:
          HP%: 0.047
          ATK%: .152
          EM: 21
          CD: 0.264
      Feather:
        Level: 20
        Set: "Crimson Witch of Flames"
        Main:
          ATK: 311
        Sub:
          DEF: 37
          DEF%: 0.051
          CR: 0.097
          CD: 0.218
      Sands:
        Level: 16
        Set: "Gladiator's Finale"
        Main:
          ATK%: 0.466
        Sub:
          CD: 0.124
          CR: 0.078
          HP: 207
          ATK: 51
      Goblet:
        Level: 20
        Set: "Maiden Beloved"
        Main:
          Pyro%: 0.466
        Sub:
          CR: 0.089
          ER: 0.052
          ATK%: 0.093
          ATK: 43
      Circlet:
        Level: 20
        Type: "Circlet"
        Set: "Gladiator's Finale"
        Main:
          CR: 0.311
        Sub:
          ATK%: 0.087
          HP%: 0.058
          CD: 0.132
          DEF: 76
  - Base:
      Name: fischl
      Level: 70
      Element: "electro"
      BaseHP: 7508
      BaseAtk: 200
      BaseDef: 485
      BaseCR: 0.05
      BaseCD: 0.50
      Constellation: 4
    AscensionBonus:
      ATK%: 0.18
    TalentLevel:
      attack: 4
      skill: 8
      burst: 2
    Weapon:
      WeaponName: "Favonius Warbow"
      WeaponRefinement: 5
      WeaponBaseAtk: 401
    WeaponSecondaryStat:
      ER%: 0.559
    Artifacts:
      Flower:
        Level: 20
        Type: "Flower"
        Set: "Wanderer's Troupe"
        Main:
          HP: 4780
        Sub:
          CD: 0.109
          ATK%: 0.087
          CR: 0.109
          ATK: 33
      Feather:
        Level: 20
        Type: "Feather"
        Set: "Wanderer's Troupe"
        Main:
          ATK: 311
        Sub:
          CD: 0.172
          ER: 0.091
          ATK%: 0.058
          CR: 0.062
      Sands:
        Level: 16
        Type: "Sands"
        Set: "Gladiator's Finale"
        Main:
          ATK%: 0.387
        Sub:
          EM: 35
          CR: 0.039
          ATK: 49
          HP: 508
      Goblet:
        Level: 20
        Type: "Goblet"
        Set: "Gladiator's Finale"
        Main:
          Electro%: 0.466
        Sub:
          ATK%: 0.105
          EM: 61
          CR: 0.027
          ER: 0.11
      Circlet:
        Level: 16
        Type: "Circlet"
        Set: "Blizzard Strayer"
        Main:
          CR: 0.258
        Sub:
          ATK%: 0.041
          ATK: 53
          ER%: 0.058
          HP: 568
  - Base:
      Name: xingqiu
      Level: 70
      Element: "hydro"
      BaseHP: 8352
      BaseAtk: 165
      BaseDef: 619
      BaseCR: 0.05
      BaseCD: 0.50
      Constellation: 6
    AscensionBonus:
      ATK%: 0.18
    TalentLevel:
      attack: 1
      skill: 8
      burst: 8
    Weapon:
      WeaponName: "Sacrificial Sword"
      WeaponRefinement: 3
      WeaponBaseAtk: 401
    WeaponSecondaryStat:
      ER: 0.559
    Artifacts:
      Flower:
        Level: 20
        Type: "Flower"
        Set: "Noblesse Oblige"
        Main:
          HP: 4780
        Sub:
          ATK: 45
          DEF: 21
          ATK%: 0.105
          CD: 0.194
      Feather:
        Level: 20
        Type: "Feather"
        Set: "Gladiator's Finale"
        Main:
          ATK: 311
        Sub:
          CD: 0.218
          DEF: 19
          ATK%: 0.117
          EM: 40
      Sands:
        Level: 20
        Type: "Sands"
        Set: "Noblesse Oblige"
        Main:
          ATK%: 0.466
        Sub:
          CR: 0.066
          HP: 209
          ER: 0.175
          DEF%: 0.109
      Goblet:
        Level: 20
        Type: "Goblet"
        Set: "Gladiator's Finale"
        Main:
          Hydro%: 0.466
        Sub:
          CD: 0.124
          HP%: 0.047
          ATK%: 0.146
          ATK: 31
      Circlet:
        Level: 16
        Type: "Circlet"
        Set: "Archaic Petra"
        Main:
          CR: 0.258
        Sub:
          HP%: 0.093
          ATK: 31
          DEF: 42
          CD: 0.14
Enemy: #blazing axe mitachurl
  Level: 88
  Resist:
    pyro: 0.1
    dendro: 0.1
    hydro: 0.1
    cryo: 0.1
    electro: 0.1
    geo: 0.1
    anemo: 0.1
    physical: 0.3
InitialActive: "xingqiu"
Rotation: >
  actions+=sequence_strict target=xingqiu exec=skill,burst lock=100;
  actions+=skill target=xingqiu if=.status.xingqiu.energy<80 lock=100;
  actions+=burst target=xingqiu;
  actions+=burst target=bennett;
  actions+=sequence_strict target=xiangling exec=skill,burst;
  actions+=skill target=xiangling active=xiangling;
  actions+=burst target=fischl if=.status.xiangling.energy<70&&.tags.fischl.oz==0 swap=xiangling;
  actions+=skill target=fischl if=.status.xiangling.energy<70&&.tags.fischl.oz==0 swap=xiangling;
  actions+=burst target=fischl if=.tags.fischl.oz==0;
  actions+=skill target=fischl if=.tags.fischl.oz==0;
  actions+=skill target=bennett if=.status.xiangling.energy<40 swap=xiangling;
  actions+=skill target=bennett;
  actions+=attack target=xiangling;
  actions+=attack target=xingqiu active=xingqiu;
  actions+=attack target=bennett active=bennett;
  actions+=attack target=fischl active=fischl;
