Label: "Test"
Characters:
  - Base:
      Name: Ganyu
      Level: 90
      Element: "cryo"
      BaseHP: 9797
      BaseAtk: 335
      BaseDef: 630
      BaseCR: 0.05
      BaseCD: 0.50
      Constellation: 0
    AscensionBonus:
      CD: 0.384
    TalentLevel:
      attack: 10
      skill: 6
      burst: 6
    Weapon:
      WeaponName: "Prototype Crescent"
      WeaponRefinement: 4
      WeaponBaseAtk: 510
    WeaponSecondaryStat:
      ATK%: 0.413
    Artifacts:
      Flower:
        Level: 20
        Type: "Flower"
        Set: "Blizzard Strayer"
        Main:
          HP: 4780
        Sub:
          EM: 21
          ATK: 47
          CD: 0.179
          DEF: 19
      Feather:
        Level: 20
        Type: "Feather"
        Set: "Blizzard Strayer"
        Main:
          ATK: 311
        Sub:
          CD: 0.062
          EM: 35
          ATK%: 0.157
          CR: 0.07
      Sands:
        Level: 20
        Type: "Sands"
        Set: "Blizzard Strayer"
        Main:
          ATK%: 0.466
        Sub:
          ATK: 31
          CD: 0.225
          HP%: 0.047
          ER: 0.168
      Goblet:
        Level: 20
        Type: "Goblet"
        Set: "Crimson Witch of Flames"
        Main:
          Cryo%: 0.466
        Sub:
          CD: 0.07
          CR: 0.093
          HP: 717
          DEF: 16
      Circlet:
        Level: 20
        Type: "Circlet"
        Set: "Blizzard Strayer"
        Main:
          CD: 0.622
        Sub:
          CR: 0.097
          DEF: 21
          ATK%: 0.14
          DEF%: 0.066
  - Base:
      Name: Diona
      Level: 70
      Element: "cryo"
      BaseHP: 8352
      BaseAtk: 165
      BaseDef: 619
      BaseCR: 0.05
      BaseCD: 0.50
      Constellation: 6
    TalentLevel:
      attack: 1
      skill: 6
      burst: 6
    Weapon:
      WeaponName: "Favonius Warbow"
      WeaponRefinement: 3
      WeaponBaseAtk: 401
    WeaponSecondaryStat:
      ER: 0.559
    Artifacts:
      Flower:
        Level: 20
        Type: "Flower"
        Set: "Gladiator's Finale"
        Main:
          HP: 4780
      Feather:
        Level: 20
        Type: "Feather"
        Set: "Gladiator's Finale"
        Main:
          ATK: 311
      Sands:
        Level: 20
        Type: "Sands"
        Set: "Thundersoother"
        Main:
          ATK%: 0.466
      Goblet:
        Level: 20
        Type: "Goblet"
        Set: "Maiden Beloved"
        Main:
          Hydro%: 0.466
      Circlet:
        Level: 16
        Type: "Circlet"
        Set: "Bloodstained Chivalry"
        Main:
          CR: 0.258
  - Base:
      Name: Bennett
      Level: 70
      Element: "pyro"
      BaseHP: 10129
      BaseAtk: 156
      BaseDef: 630
      BaseCR: 0.05
      BaseCD: 0.50
      Constellation: 2
    AscensionBonus:
      ER: 0.2
    TalentLevel:
      attack: 2
      skill: 3
      burst: 6
    Weapon:
      WeaponName: "Festering Desire"
      WeaponRefinement: 5
      WeaponBaseAtk: 510
    WeaponSecondaryStat:
      ER: 0.459
    Artifacts:
      Flower:
        Level: 16
        Set: "Noblesse Oblige"
        Main:
          HP: 3967
        Sub:
          DEF: 44
          ER: 0.065
          CR: 0.097
          CD: 0.07
      Feather:
        Level: 16
        Set: "Noblesse Oblige"
        Main:
          ATK: 258
        Sub:
          ATK%: .117
          DEF: 16
          ER: 0.104
          EM: 42
      Sands:
        Level: 16
        Set: "Noblesse Oblige"
        Main:
          ER: 0.43
        Sub:
          ATK%: 0.163
          HP%: 0.058
          CD: 0.117
          HP: 209
      Goblet:
        Level: 16
        Set: "Noblesse Oblige"
        Main:
          ATK%: 0.387
        Sub:
          ER: 0.097
          HP: 538
          CR: 0.031
          EM: 35
      Circlet:
        Level: 20
        Set: "Thundering Fury"
        Main:
          ATK%: 0.387
        Sub:
          EM: 63
          HP: 209
          CR: 0.031
          ATK: 35
  - Base:
      Name: Xiangling
      Level: 80
      Element: "pyro"
      BaseHP: 9638
      BaseAtk: 200
      BaseDef: 593
      BaseCR: 0.05
      BaseCD: 0.50
      Constellation: 6
    AscensionBonus:
      EM: 72
    TalentLevel:
      attack: 6
      skill: 6
      burst: 8
    Weapon:
      WeaponName: "Skyward Spine"
      WeaponRefinement: 1
      WeaponBaseAtk: 674
    WeaponSecondaryStat:
      ER: 0.368
    Artifacts:
      Flower:
        Level: 20
        Set: "Crimson Witch of Flames"
        Main:
          HP: 4780
        Sub:
          HP%: 0.047
          ATK%: .152
          EM: 21
          CD: 0.264
      Feather:
        Level: 20
        Set: "Crimson Witch of Flames"
        Main:
          ATK: 311
        Sub:
          DEF: 37
          DEF%: 0.051
          CR: 0.097
          CD: 0.218
      Sands:
        Level: 16
        Set: "Noblesse Oblige"
        Main:
          ATK%: 0.387
        Sub:
          ATK: 37
          DEF: 23
          HP%: 0.099
          ER: 0.168
      Goblet:
        Level: 20
        Set: "Maiden Beloved"
        Main:
          Pyro%: 0.466
        Sub:
          CR: 0.089
          ER: 0.052
          ATK%: 0.093
          ATK: 43
      Circlet:
        Level: 20
        Type: "Circlet"
        Set: "Noblesse Oblige"
        Main:
          CR: 0.232
        Sub:
          CD: 0.056
          ATK: 28
          EM: 30
          DEF%: 0.053
Enemy:
  Level: 88
  Resist:
    pyro: 0.1
    dendro: 0.1
    hydro: 0.1
    cryo: 0.1
    electro: 0.1
    geo: 0.1
    anemo: 0.1
    physical: 0.1
InitialActive: "Bennett"
Rotation:
  - CharacterName: "Bennett"
    Action: "burst"
  - CharacterName: "Xiangling"
    Action: "burst"
  - CharacterName: "Ganyu"
    Action: "skill"
  - CharacterName: "Ganyu"
    Action: "burst"
  - CharacterName: "Ganyu"
    Action: "aimed"
  - CharacterName: "Xiangling"
    Action: "skill"
  - CharacterName: "Bennett"
    Action: "attack"
