Label: "Test"
Characters:
  - Base:
      Name: Eula
      Level: 90
      Element: "cryo"
      BaseHP: 13226
      BaseAtk: 342
      BaseDef: 751
      BaseCR: 0.05
      BaseCD: 0.50
      Constellation: 0
    AscensionBonus:
      CD: 0.384
    TalentLevel:
      attack: 8
      skill: 6
      burst: 9
    Weapon:
      WeaponName: "Skyward Pride"
      WeaponRefinement: 1
      WeaponBaseAtk: 674
    WeaponSecondaryStat:
      ER: 0.368
    Artifacts:
      Flower:
        Level: 20
        Set: "Gladiator's Finale"
        Main:
          HP: 4780
      Feather:
        Level: 20
        Set: "Gladiator's Finale"
        Main:
          ATK: 311
      Sands:
        Level: 20
        Set: "Bloodstained Chivalry"
        Main:
          ATK%: 0.466
      Goblet:
        Level: 20
        Set: "Bloodstained Chivalry"
        Main:
          Phys%: 0.466
      Circlet:
        Level: 20
        Set: "Bloodstained Chivalry"
        Main:
          CR: 0.311
Enemy:
  Level: 88
  Resist:
    pyro: 0.1
    dendro: 0.1
    hydro: 0.1
    cryo: 0.1
    electro: 0.1
    geo: 0.1
    anemo: 0.1
    physical: 0.1
InitialActive: "Eula"
Rotation:
  - CharacterName: "Eula"
    Action: "burst"
    SwapLock: 480
  - CharacterName: "Eula"
    Action: "skill"
    Params: 1
    ConditionType: "tags"
    ConditionTarget: "Grimheart"
    ConditionInt: 2
  - CharacterName: "Eula"
    Action: "skill"
  - CharacterName: "Eula"
    Action: "attack"